{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "consumeroffsetmonitoring.serviceAccountName" . }}
  labels:
{{ include "consumeroffsetmonitoring.labels" . | indent 4 }}
{{- end -}}
