apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ template "druid.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.broker.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "druid.broker.fullname" . }}
spec:
  serviceName: {{ template "druid.broker.fullname" . }}
  replicas: {{ .Values.broker.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "druid.name" . }}
      release: {{ .Release.Name }}
      component: {{ .Values.broker.name }}
  template:
    metadata:
      labels:
        app: {{ template "druid.name" . }}
        component: {{ .Values.broker.name }}
        release: {{ .Release.Name }}
        {{- with .Values.broker.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
        {{- end }}
    spec:
      {{- if or .Values.broker.antiAffinity .Values.broker.nodeAffinity }}
      affinity:
      {{- end }}
      {{- if eq .Values.broker.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: "{{ template "druid.name" . }}"
                  release: "{{ .Release.Name }}"
                  component: "{{ .Values.broker.name }}"
      {{- else if eq .Values.broker.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "{{ template "druid.name" . }}"
                  release: "{{ .Release.Name }}"
                  component: "{{ .Values.broker.name }}"
      {{- end }}
      {{- with .Values.broker.nodeAffinity }}
        nodeAffinity:
{{ toYaml . | indent 10 }}
      {{- end }}
{{- if .Values.broker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.broker.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.broker.tolerations }}
      tolerations:
{{ toYaml .Values.broker.tolerations | indent 8 }}
{{- end }}
      containers:
      - name: druid
        args: [ "broker" ]
        env:
        {{- if .Values.zookeeper.enabled }}
        - name: ZOOKEEPER_HOST
          value: {{ .Release.Name }}-cp-zookeeper-headless:2181
        {{- else }}
        - name: ZOOKEEPER_HOST
          value: {{ .Release.Name }}-cp-zookeeper-headless:2181
        {{- end }}
        {{- if .Values.mysql.enabled }}
        - name: DB_HOST
          value: {{ .Release.Name }}-mysql
        - name: DB_TYPE
          value: mysql
        - name: DB_USERNAME
          value: {{ .Values.mysql.mysqlUser }}
        - name: DB_PASSWORD
          value: {{ .Values.mysql.mysqlPassword }}
        - name: DB_DBNAME
          value: {{ .Values.mysql.mysqlDatabase }}
        - name: DB_PORT
          value: "3306"
        {{- end }}
        - name: JAVA_OPTS
          value: {{ .Values.broker.javaOpts }}
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: druid_extensions_loadList
          value: '["postgresql-metadata-storage", "druid-kafka-indexing-service", "druid-avro-extensions"]'
        resources:
{{ toYaml .Values.broker.resources | indent 12 }}
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /status/health
            port: {{ .Values.broker.port }}
        readinessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /status/health
            port: {{ .Values.broker.port }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: {{ .Values.broker.port }}
          name: http
        volumeMounts:
        - mountPath: /opt/druid/var
          name: data
  {{- if not .Values.broker.persistence.enabled }}
      volumes:
      - name: data
        emptyDir: {}
  {{- end }}
  updateStrategy:
    type: {{ .Values.broker.updateStrategy.type }}
  {{- if .Values.broker.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - {{ .Values.broker.persistence.accessMode | quote }}
    {{- if .Values.broker.persistence.storageClass }}
    {{- if (eq "-" .Values.broker.persistence.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.broker.persistence.storageClass }}"
    {{- end }}
    {{- end }}
      resources:
        requests:
          storage: "{{ .Values.broker.persistence.size }}"
  {{ end }}
